### ISSUE TITLE
only publish the  latest release change logs

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend-docs#185]
The nightly mainly for developer not for user, the latest release is for the user and the change logs are all from the previous latest release, so we should only publish the latest release change logs.

The action is check the `Set as the latest release`:
<img width="465" alt="image" src="https://github.com/datafuselabs/databend-docs/assets/172204/ea6efbe7-3f75-4e79-96b0-8a913ebe4e81">

**Comment by BohuTANG** [comment]
@Chasen-Zhang 

This page should only show the stable(latest release) version and his change logs:
https://docs.databend.com/download

The latest release is:
https://github.com/datafuselabs/databend/releases/tag/v1.2.233-nightly

![image](https://github.com/datafuselabs/databend-docs/assets/172204/39c42078-8424-4882-88d9-eb9a2765f1e2)

**Comment by Chasen-Zhang** [comment]
@BohuTANG Sorry, I modified your content, the deleted link is:
https://databend.rs/download
https://github.com/datafuselabs/databend/releases/tag/v1.2.233-nightly

**Comment by BohuTANG** [comment]
@Chasen-Zhang we only show the versions who name is not **-nightly** is ok, it means it's a stable version.

**Comment by Chasen-Zhang** [comment]
> @Chasen-Zhang we only show the versions who name is not **-nightly** is ok, it means it's a stable version. For example: <img alt="image" width="280" src="https://private-user-images.githubusercontent.com/172204/289448225-1f1b3afe-69fa-49ff-ad63-d833ba886c87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNzc1OTcsIm5iZiI6MTcwMjI3NzI5NywicGF0aCI6Ii8xNzIyMDQvMjg5NDQ4MjI1LTFmMWIzYWZlLTY5ZmEtNDlmZi1hZDYzLWQ4MzNiYTg4NmM4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQwNjQ4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmMwYjkzYjZkOWRjZjY5YjNjMGU4N2I2MDI1MTAyMTI4YmExMzQ0ODAwNDg5NGFiYTMzNmM2ZmRiZDkyNzg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KrkGETe2-ePkQezPL1ivH94Fu9LwXjmGM3UL_WApQVY">

OK
