### ISSUE TITLE
Change the title of the releases

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend-docs#215]
Now, all the releases should be stable, so we can change the sidebar title:
<img width="1087" alt="image" src="https://github.com/datafuselabs/databend-docs/assets/172204/f0f32f30-5701-4a68-b550-190c7e3e43bd">

The release markdown dir should be: https://github.com/datafuselabs/databend-docs/tree/main/docs/release-stable
We can remove the `docs/release-nightly`.

**Comment by Chasen-Zhang** [comment]
fixed: https://github.com/datafuselabs/databend-docs/pull/217
