### ISSUE TITLE
Add `secure` param to databend_py docs

### ISSUE THREAD

**Issue by hantmac** [datafuselabs/databend-docs#222]
![img_v3_0264_296d88f0-c7a8-491d-935e-c025ffbb265g](https://github.com/datafuselabs/databend-docs/assets/7600925/9fc00b64-0bf8-4cd1-8045-0a628536811f)

Add the `secure` param to databend_py in dsn as shown in picture.

**Comment by soyeric128** [comment]
https://github.com/datafuselabs/databend-docs/pull/223
