### ISSUE TITLE
ci: add lychee for link checking

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/databend-docs#273]
- https://github.com/lycheeverse/lychee-action
- https://github.com/lycheeverse/lychee

Need to filter links with rate limits, such as npm and github.
In addition, it may be necessary to modify the links related to accessing images and other resources.

**Comment by BohuTANG** [comment]
Let's make this issue as high-priority.

**Comment by PsiACE** [comment]
Just conducted a simple test, we now have over 100,000 links in build dir. I will find a relatively sensible way to handle it.

**Comment by PsiACE** [comment]
After removing any irrelevant files and only checking markdown, I obtained an interim result. There are some files that are not actual errors, but rather related to the way paths are written. I will carefully examine them.

```
🔍 5838 Total ✅ 3524 OK 🚫 816 Errors (HTTP:816) 💤 1470 Excluded
```

**Comment by PsiACE** [comment]
```
🔍 7474 Total (in 31s) ✅ 2646 OK 🚫 104 Errors 💤 4724 Excluded
```

Some of the errors are due to restrictions such as IP conditions, which should be better addressed in CI. After it runs, we can make targeted fixes.

In addition, I have added fail-fast checks to avoid introducing new broken links directly.
