### ISSUE TITLE
docs: integrate the udf server into docs

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend-docs#3]
currently we have an README about the UDF server, but it cannot be found in the databend.rs docs.

https://github.com/datafuselabs/databend/tree/main/tests/udf-server

there's also a shortcoming in this README, is that which sdk should I install? we'd better release a package into the pypi registry.

**Comment by soyeric128** [comment]
https://databend.rs/doc/sql-commands/ddl/external-function/

This page has been updated for information about the pip package [databend-udf](https://pypi.org/project/databend-udf), along with a practical example similar to the README you referred above.

**Comment by BohuTANG** [comment]
Thanks @soyeric128 , but looks like we missed the part how to use it in Cloud.

**Comment by soyeric128** [comment]
> Thanks @soyeric128 , but looks like we missed the part how to use it in Cloud.

@flaneur2020 @everpcpc Can you help provides some input on how to set up an external function? Such as how to enable the feature and set allowed IP list? Thanks.

**Comment by everpcpc** [comment]
Setting allowed IP list is an admin operation, and should be requested by creating ticket.

**Comment by soyeric128** [comment]
Added a note in step 1: https://databend.rs/doc/sql-commands/ddl/external-function/#creating-an-external-function-in-python
