### ISSUE TITLE
Update docs for python driver

### ISSUE THREAD

**Issue by everpcpc** [datafuselabs/databend-docs#30]
change to https://pypi.org/project/databend-driver/

**Comment by soyeric128** [comment]
@everpcpc Can u help confirm if [databend-sqlalchemy](https://github.com/datafuselabs/databend-sqlalchemy) is still recommended?

**Comment by everpcpc** [comment]
Yes, `databend-sqlalchemy` is a different library from `databend-driver`, and still available.

**Comment by soyeric128** [comment]
https://github.com/datafuselabs/databend-docs/pull/32
