### ISSUE TITLE
Bug of `JSON_PATH_MATCH` function

### ISSUE THREAD

**Issue by JasonLi-cn** [datafuselabs/databend-docs#307]
### Doc

https://github.com/datafuselabs/databend-docs/blob/2d085463fa4896bdbe81150fb27e875bdf759887/docs/sql-reference/20-sql-functions/10-semi-structured-functions/json-path-match.md?plain=1#L48-L56

### My Test

Change json_path_expression from `'$.b[1 to last] >= 2'` to `'$.b[1 to last] > 2'`, expected result is `0`, but return `1`

```shell
mysql> SELECT JSON_PATH_MATCH(parse_json('{"a":1,"b":[1,2,3]}'), '$.b[1 to last] > 2');
+--------------------------------------------------------------------------+
| json_path_match(parse_json('{"a":1,"b":[1,2,3]}'), '$.b[1 to last] > 2') |
+--------------------------------------------------------------------------+
|                                                                        1 |
+--------------------------------------------------------------------------+
```

### Reason

crate `jsonb`:
https://github.com/datafuselabs/jsonb/blob/582c139d884248bcb357e995d8ea4501fc264e60/src/jsonpath/selector.rs#L530-L537

### Modification suggestion

- a. Change `Check if all elements in the array` to `Check if any one element in the array`.
- b. Modify compare function logical in `jsonb` crate.

**Comment by soyeric128** [comment]
Well spotted. Fixed: https://docs.databend.com/sql/sql-functions/semi-structured-functions/json-path-match#examples

Thank you.
