### ISSUE TITLE
feat: Collect frequently asked questions from users

### ISSUE THREAD

**Issue by Chasen-Zhang** [datafuselabs/databend-docs#315]
I need your help to provide some content @wubx 

related: https://github.com/datafuselabs/databend/issues/14205

**Comment by Chasen-Zhang** [comment]
https://docs.databend.cn/guides/overview/faq

**Comment by PsiACE** [comment]
> https://docs.databend.cn/guides/overview/faq

https://docs.databend.com/guides/overview/faq
