### ISSUE TITLE
add CREATE PASSWORD POLICY

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend-docs#433]
It seems https://docs.databend.com/guides/security/password-policy is not enough.

Full:
```
CREATE PASSWORD POLICY test_policy
    PASSWORD_MIN_LENGTH = 12
    PASSWORD_MAX_LENGTH = 24
    PASSWORD_MIN_UPPER_CASE_CHARS = 2
    PASSWORD_MIN_LOWER_CASE_CHARS = 2
    PASSWORD_MIN_NUMERIC_CHARS = 2
    PASSWORD_MIN_SPECIAL_CHARS = 2
    PASSWORD_MIN_AGE_DAYS = 1
    PASSWORD_MAX_AGE_DAYS = 30
    PASSWORD_MAX_RETRIES = 3
    PASSWORD_LOCKOUT_TIME_MINS = 30
    PASSWORD_HISTORY = 5
    COMMENT = 'test comment'
```

https://github.com/datafuselabs/databend/pull/14012/files#diff-d04de3cef27f9ba12c2be2e3791edc09c122b5af72cb83a81f5d0049a0fbdc58R11

**Comment by BohuTANG** [comment]
cc @b41sh  for a check:
```
CREATE PASSWORD POLICY test_policy
    PASSWORD_MIN_LENGTH = 12
    PASSWORD_MAX_LENGTH = 24
    PASSWORD_MIN_UPPER_CASE_CHARS = 2
    PASSWORD_MIN_LOWER_CASE_CHARS = 2
    PASSWORD_MIN_NUMERIC_CHARS = 2
    PASSWORD_MIN_SPECIAL_CHARS = 2
    PASSWORD_MIN_AGE_DAYS = 1
    PASSWORD_MAX_AGE_DAYS = 30
    PASSWORD_MAX_RETRIES = 3
    PASSWORD_LOCKOUT_TIME_MINS = 30
    PASSWORD_HISTORY = 5
    COMMENT = 'test comment'
```

All these we have support?

**Comment by soyeric128** [comment]
I didn't set all attributes in the example because all of them come with a default value:

https://docs.databend.com/sql/sql-commands/ddl/password-policy/create-password-policy#password-policy-attributes

**Comment by b41sh** [comment]
> cc @b41sh for a check:
> 
> ```
> CREATE PASSWORD POLICY test_policy
>     PASSWORD_MIN_LENGTH = 12
>     PASSWORD_MAX_LENGTH = 24
>     PASSWORD_MIN_UPPER_CASE_CHARS = 2
>     PASSWORD_MIN_LOWER_CASE_CHARS = 2
>     PASSWORD_MIN_NUMERIC_CHARS = 2
>     PASSWORD_MIN_SPECIAL_CHARS = 2
>     PASSWORD_MIN_AGE_DAYS = 1
>     PASSWORD_MAX_AGE_DAYS = 30
>     PASSWORD_MAX_RETRIES = 3
>     PASSWORD_LOCKOUT_TIME_MINS = 30
>     PASSWORD_HISTORY = 5
>     COMMENT = 'test comment'
> ```
> 
> All these we have support?

yes, we have support all those options.

**Comment by b41sh** [comment]
> I didn't set all attributes in the example because all of them come with a default value:
> 
> https://docs.databend.com/sql/sql-commands/ddl/password-policy/create-password-policy#password-policy-attributes

we can use some different options as example.
