### ISSUE TITLE
OpenDAL's cache layer in Databend

### ISSUE THREAD

**Issue by xiaguan** [datafuselabs/databend-docs#473]
I was reading the design documentation for the caching mechanism and noticed a mention of support for a cache layer of 'OpenDAL'. However, while going through the 'Databend' code, I couldn't seem to find any implementation or reference to this.

**Comment by PsiACE** [comment]
The fact is, we have not planned to fully utilize the cache layer of opendal. Currently, the cache is managed by Databend. If necessary, a controlled cache layer can be customized for opendal.

**Comment by xiaguan** [comment]
Thanks, I understand now. I'll try to establish a cache layer on top of opendal.
