### ISSUE TITLE
create or replace

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend-docs#486]
- [x] stage: https://github.com/datafuselabs/databend/pull/14548
- [x] connection: https://github.com/datafuselabs/databend/pull/14580
- [x] table: https://github.com/datafuselabs/databend/pull/14508
- [x] database: https://github.com/datafuselabs/databend/pull/14449
- [x] https://github.com/datafuselabs/databend/pull/14654
- [x] https://github.com/datafuselabs/databend/pull/14649
- [x] https://github.com/datafuselabs/databend/pull/14636
- [x] https://github.com/datafuselabs/databend/pull/14611
- [x] https://github.com/datafuselabs/databend/pull/14599
- [x] https://github.com/datafuselabs/databend/pull/14583
- [x] https://github.com/datafuselabs/databend/pull/14596
- [x] https://github.com/datafuselabs/databend/pull/14654
- [x] https://github.com/datafuselabs/databend/pull/14658
- [x] https://github.com/datafuselabs/databend/pull/14660

**Comment by PsiACE** [comment]
function(udf): https://github.com/datafuselabs/databend/pull/14581

**Comment by BohuTANG** [comment]
This issue is all done.
