### ISSUE TITLE
Explain GCS credential requirement

### ISSUE THREAD

**Issue by rad-pat** [datafuselabs/databend-docs#569]
The documentation does not explain that the GCS credentials to be supplied in the `credential` config should be the base64 encoded JSON credentials obtained from 
```
gcloud iam service-accounts keys create ~/path/to/your/key-file.json --iam-account <YOUR_SERVICE_ACCOUNT_NAME>@<YOUR_PROJECT_ID>.iam.gserviceaccount.com
```

**Comment by soyeric128** [comment]
Thanks for spotting this. Fixed: https://docs.databend.com/guides/deploy/deploying-databend#setting-up-your-object-storage
