### ISSUE TITLE
vacuum table dry run result

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend-docs#608]
There are two main changes in `vacuum` syntax:
* `vacuum table <table_name>` returns the result table, PR https://github.com/datafuselabs/databend/pull/14830
* `vacuum table ... dry run summary` returns the summary, PR https://github.com/datafuselabs/databend/pull/14851

**Comment by soyeric128** [comment]
Updated: https://docs.databend.com/sql/sql-commands/ddl/table/vacuum-table
