### ISSUE TITLE
add documents for histogram aggregate functions

### ISSUE THREAD

**Issue by suimenno3002** [datafuselabs/databend-docs#636]
I think we should add documents for histogram aggregate functions, it would be proper to assign it to me.
References:
- https://github.com/datafuselabs/databend/pull/14839
- https://github.com/datafuselabs/databend/issues/14588

**Comment by soyeric128** [comment]
There you go

**Comment by soyeric128** [comment]
https://github.com/datafuselabs/databend-docs/pull/680
