### ISSUE TITLE
docs: add description about how to get the GCS credential

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend-docs#771]
![Screenshot 2024-05-07 at 15 34 29](https://github.com/datafuselabs/databend-docs/assets/129800/74883125-e516-4433-8de6-994e29ca77ad)

the `credential` is essential to get GCS connected, but it's hard for us to memorize how to get the credential from GCS.

it'd be better to have a link about how to get the credential in the docs.

**Comment by flaneur2020** [comment]
> Follow the topic [Create a service account key](https://cloud.google.com/iam/docs/keys-create-delete#creating) from the Google documentation to create and download a service account key file.
> Utilize Base64 encoding to convert the contents of the service account key file into a Base64-encoded string. For example,
base64 -i <path-to-your-key-file> -o ~/Desktop/base64-encoded-key.txt

**Comment by BohuTANG** [comment]
There is a description here:
https://docs.databend.com/guides/deploy/deploy/non-production/deploying-databend

<img width="839" alt="image" src="https://github.com/datafuselabs/databend-docs/assets/172204/3c0284c8-3f7a-4ea7-98b9-16626b58e2b2">

**Comment by PsiACE** [comment]
#772
