### ISSUE TITLE
change the translate api from openai to deepseek

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend-docs#777]
https://platform.deepseek.com/docs

**Comment by BohuTANG** [comment]
@PsiACE any suggestions?

**Comment by PsiACE** [comment]
> @PsiACE any suggestions?

Cool, the only thing to consider is API compatibility. If it is compatible with OpenAI's API, I think it will be easy. Otherwise, we may need to do some simple development ourselves.
