### ISSUE TITLE
doc: add transaction

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend-docs#815]
BEGIN/COMMIT/ROLLBACK

**Comment by BohuTANG** [comment]
https://github.com/datafuselabs/databend/pull/14562/files#diff-f269127d10d7a88c990c5a64b3d823348bc83ad309788f6293c5bef043380f35

**Comment by soyeric128** [comment]
Welcome to BendSQL 0.12.5-61a19d7(2024-01-25T02:44:25.884223000Z).
Connecting to localhost:8000 as user root.
Connected to Databend Query v1.2.515-nightly-159a8b8547(rust-1.78.0-nightly-2024-06-05T09:26:43.846173960Z)

root@localhost:8000/default> CREATE TABLE employees (
    id INT,
    name VARCHAR(50),
    department VARCHAR(50)
);

CREATE TABLE employees (
  id INT,
  name VARCHAR(50),
  department VARCHAR(50)
)

0 row written in 0.039 sec. Processed 0 row, 0 B (0 row/s, 0 B/s)

root@localhost:8000/default> begin;

BEGIN

0 row read in 0.016 sec. Processed 0 row, 0 B (0 row/s, 0 B/s)

root@localhost:8000/default> INSERT INTO employees (id, name, department) VALUES (1, 'Alice', 'HR');

INSERT INTO
  employees (id, name, department)
VALUES
  (1, 'Alice', 'HR')

1 row written in 0.055 sec. Processed 1 row, 46 B (18.29 row/s, 841 B/s)

root@localhost:8000/default> INSERT INTO employees (id, name, department) VALUES (2, 'Bob', 'Engineering');

INSERT INTO
  employees (id, name, department)
VALUES
  (2, 'Bob', 'Engineering')

1 row written in 0.043 sec. Processed 1 row, 53 B (23.12 row/s, 1.20 KiB/s)

root@localhost:8000/default> UPDATE employees SET department = 'Finance' WHERE id = 1;

UPDATE
  employees
SET
  department = 'Finance'
WHERE
  id = 1

1 row written in 0.085 sec. Processed 1 row, 0 B (11.71 row/s, 0 B/s)

root@localhost:8000/default> ROLLBACK;

ROLLBACK

0 row read in 0.013 sec. Processed 0 row, 0 B (0 row/s, 0 B/s)

root@localhost:8000/default> SELECT * FROM employees;

SELECT
  *
FROM
  employees

┌───────────────────────────────────────────────────────┐
│        id       │       name       │    department    │
│ Nullable(Int32) │ Nullable(String) │ Nullable(String) │
├─────────────────┼──────────────────┼──────────────────┤
│               1 │ Alice            │ Finance          │
│               2 │ Bob              │ Engineering      │
└───────────────────────────────────────────────────────┘
2 rows read in 0.028 sec. Processed 2 rows, 104 B (72.35 rows/s, 3.67 KiB/s)

**Comment by soyeric128** [comment]
Verified the example above on Databend n Databend Cloud:

- ROLLBACK seems not working on Databend. 
- The example worked fine on Databend Cloud.
