### ISSUE TITLE
add document for updated query configs

### ISSUE THREAD

**Issue by ZhiHanZ** [datafuselabs/databend-docs#847]
https://docs.databend.com/guides/deploy/references/node-config/query-config#query-section

we need to mention settings and other missing fields which updated recently

**Comment by soyeric128** [comment]
- https://github.com/datafuselabs/databend/pull/14475/files
- https://github.com/datafuselabs/databend/commit/0e3b8a60778d74210ddc9af94475e67e2e3016a9#diff-48fcd360626e36be1854ab38174e53f45fa13cbba66176db5510e6e089665203
- https://github.com/datafuselabs/databend/commit/3f532a2f0ae4ed61929d2bad3e73837efec84cff

**Comment by soyeric128** [comment]
Added these parameters to https://docs.databend.com/guides/deploy/references/node-config/query-config#query-section

- aggregate_spilling_memory_ratio
- join_spilling_memory_ratio
- max_running_queries
- data_retention_time_in_days_max
